# Generated by Django 4.2.7 on 2024-11-06 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="author",
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id_author",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "books",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.books"
                    ),
                ),
            ],
        ),
    ]
